### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/opencerts-website#109]
I have compilation error after clone the latest repository and run yarn dev.  I do not have this error when I use the previous version of the repository.   I am running it on windows. 

git clone https://github.com/GovTechSG/opencerts-website.git
npm install 
yarn dev
---------------------------------- 
yarn run v1.12.3
$ next
Defining routes from exportPathMap

Compiling
√ success server compiled in 21s 381ms
√ success client compiled in 16s 280ms

 DONE  Compiled successfully in 32378ms                                                                      12:27:56 AM

> Ready on http://localhost:3000

 WAIT  Compiling...                                                                                          12:27:57 AM

√ success client compiled in 3s 151ms

 DONE  Compiled successfully in 4295ms                                                                       12:28:01 AM

> Building page: /

 WAIT  Compiling...
√ success server compiled in 6s 560ms
√ success client compiled in 7s 155ms

 ERROR  Failed to compile with 7 errors                                                                      12:28:25 AM

 error  in ./src/components/Layout/footer.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/Layout/FooterBar.js 4:0-32 9:8-11 16:15-18 23:15-18
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/HomePageContent/aboutSection.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/HomePageContent/AboutSection.js 3:0-38 8:15-18 21:15-18 35:15-18 42:15-18 49:15-18 69:15-18 76:15-18 83:15-18 103:15-18 110:15-18 117:15-18 146:10-13 161:15-18 168:15-18 186:8-11 193:15-18 214:15-18 221:15-18
 @ ./src/components/MainPageContainer.js
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/HomePageContent/dropZoneSection.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/HomePageContent/DropZoneSection.js 5:0-41 18:15-18 32:15-18
 @ ./src/components/MainPageContainer.js
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/HomePageContent/partnersPage.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/HomePageContent/PartnersSection.js 3:0-38 54:17-20 64:10-13 85:8-11 92:15-18
 @ ./src/components/MainPageContainer.js
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/Layout/networkSelector.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/Layout/NetworkSelector.js 26:0-41 58:19-22
 @ ./src/components/Layout/FooterBar.js
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/Layout/NavigationBar/navBar.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/Layout/NavigationBar/NavigationBar.js 4:0-32 18:27-30 18:74-77 47:25-28 54:15-18 77:15-18 90:25-28
 @ ./src/components/Layout/NavigationBar/index.js
 @ ./pages/index.js
 @ multi ./pages/index.js

 error  in ./src/components/CertificateDropZone/Views/viewerStyles.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir 'D:\opencerts-website\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (D:\opencerts-website\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (D:\opencerts-website\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\opencerts-website\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\opencerts-website\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (D:\opencerts-website\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\opencerts-website\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\opencerts-website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at runLoaders (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:286:20)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:172:11
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:32:11)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (D:\opencerts-website\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\opencerts-website\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\opencerts-website\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:618:10)
    at moduleFactory.create (D:\opencerts-website\node_modules\webpack\lib\Compilation.js:996:12)
    at factory (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\opencerts-website\node_modules\webpack\lib\NormalModuleFactory.js:155:13)

 @ ./src/components/CertificateDropZone/Views/UnverifiedView.js 5:0-38 14:25-28 14:74-77 14:88-91 25:15-18 56:15-18 63:15-18 70:15-18 77:15-18 90:15-18 110:15-18 117:15-18 137:15-18 162:15-18
 @ ./src/components/CertificateDropZone/CertificateDropZone.js
 @ ./src/components/CertificateDropZone/CertificateDropZoneContainer.js
 @ ./src/components/CertificateDropZone/index.js
 @ ./src/components/HomePageContent/DropZoneSection.js
 @ ./src/components/MainPageContainer.js
 @ ./pages/index.js
 @ multi ./pages/index.js

**Comment by rjchow** [comment]
try running npm install

**Comment by RP-OIS-SK** [comment]
I have already run npm install and no error before running yarn dev.

**Comment by rjchow** [comment]
This is a fresh clone, not on top of a previous clone yea? I'll have a go on my windows machine in the afternoon today

**Comment by RP-OIS-SK** [comment]
This is a fresh clone.  I have renamed the original folder.

**Comment by rjchow** [comment]
Managed to reproduce and troubleshoot this
Do `npm rebuild` , looks like there's a bug in the npm software where sometimes the modules aren't built properly

**Comment by RP-OIS-SK** [comment]
Thank you. It is working now.
