### ISSUE TITLE
The cli tool to add new templates is bugged 

### ISSUE THREAD

**Issue by raulgomezc** [OpenCerts/opencerts-website#284]
When running `npm run dev-cli`, the client hangs like this:

```sh
raulgomez@Rauls-MacBook-Pro:~/projects/opencerts-website(SIPMM)$ npm run dev-cli 

> opencerts-website@2.0.0 dev-cli /Users/raulgomez/projects/opencerts-website
> node -r esm ./scripts/cli.js

? Operation? Add a template
? Organisation Domain Name? e.g: moe.edu.sg ex.edu.sg
? Template Name? (this is the value that will be in your certificate file) e.g: 2019-Feb-GovTech-Opencerts-
Associate 2019-May-Ex
? Organisation Domain Name: ex.edu.sg, Template Name: 2019-May-Ex 
 Folder will be created at /Users/raulgomez/projects/opencerts-website/src/components/CertificateTem
plates/tlds/sg/edu/ex/2019-May-Ex Yes
TypeError: item.isDirectory is not a function
    at dirListing.filter.item (/Users/raulgomez/projects/opencerts-website/scripts/addNewTemplate.js:32:41)
    at Array.filter (<anonymous>)
    at getSubDirs (/Users/raulgomez/projects/opencerts-website/scripts/addNewTemplate.js:32:21)
    at generateTldsIndex (/Users/raulgomez/projects/opencerts-website/scripts/addNewTemplate.js:145:19)
    at addNewTemplate (/Users/raulgomez/projects/opencerts-website/scripts/addNewTemplate.js:182:54)
    at inquirer.prompt.then.confirmation (/Users/raulgomez/projects/opencerts-website/scripts/addNewTemplate.js:237:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
raulgomez@Rauls-MacBook-Pro:~/projects/opencerts-website(SIPMM)$ 
```

**Comment by rjchow** [comment]
thanks! will investigate this

**Comment by sumitnitsurat** [comment]
Can not reproduce the issue in master branch. Can you please sync with master and try again?
 
```
MacBook-Pro-de-Sumit:opencerts-website sumitchaudhari$ npm run dev-cli

> opencerts-website@2.0.0 dev-cli /Users/sumitchaudhari/govtech/opencerts-website
> node -r esm ./scripts/cli.js

? Operation? Add a template
? Organisation Domain Name? e.g: moe.edu.sg ex.edu.sg
? Template Name? (this is the value that will be in your certificate file) e.g: 2019-Feb-GovTech-Opencerts-Associate 2019-May-Ex
? Organisation Domain Name: ex.edu.sg, Template Name: 2019-May-Ex 
 Folder will be created at /Users/sumitchaudhari/govtech/opencerts-website/src/components/CertificateTemplates/tlds/sg/edu/ex/2019-
May-Ex Yes
MacBook-Pro-de-Sumit:opencerts-website sumitchaudhari$ 
```

**Comment by raulgomezc** [comment]
What version of `node` are you on?

**Comment by raulgomezc** [comment]
Fixed, the issue was the node version, maybe adding it to the readme? Closing the issue
