### ISSUE TITLE
Bug: Fails to install on node version 12.14

### ISSUE THREAD

**Issue by simboonlong** [OpenCerts/opencerts-website#470]
macOS 10.14.6 (18G95)

**Comment by Nebulis** [comment]
error log ?

**Comment by Nebulis** [comment]
#472

**Comment by rjchow** [comment]
> nvm use 12 && npm i 


```
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rjc/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by Nebulis** [comment]
Issue is caused by keccak

```
❯ npm ls keccak
opencerts-website@2.0.0 /home/nebulis/IdeaProjects/opencerts-website
├─┬ ethereumjs-util@6.1.0
│ └── keccak@1.4.0 
└─┬ web3-provider-engine@14.0.6
  ├─┬ eth-block-tracker@3.0.1
  │ └─┬ ethereumjs-util@5.2.0
  │   └── keccak@1.4.0  deduped
  ├─┬ eth-json-rpc-infura@3.2.0
  │ └─┬ eth-json-rpc-middleware@1.6.0
  │   ├─┬ eth-tx-summary@3.2.4
  │   │ └─┬ ethereumjs-util@5.2.0
  │   │   └── keccak@1.4.0  deduped
  │   └─┬ ethereumjs-util@5.2.0
  │     └── keccak@1.4.0  deduped
  ├─┬ eth-sig-util@1.4.2
  │ └─┬ ethereumjs-util@5.2.0
  │   └── keccak@1.4.0  deduped
  ├─┬ ethereumjs-block@1.7.1
  │ ├─┬ ethereumjs-util@5.2.0
  │ │ └── keccak@1.4.0  deduped
  │ └─┬ merkle-patricia-tree@2.3.2
  │   └─┬ ethereumjs-util@5.2.0
  │     └── keccak@1.4.0  deduped
  ├─┬ ethereumjs-tx@1.3.7
  │ └─┬ ethereumjs-util@5.2.0
  │   └── keccak@1.4.0  deduped
  ├─┬ ethereumjs-util@5.2.0
  │ └── keccak@1.4.0  deduped
  └─┬ ethereumjs-vm@2.6.0
    ├─┬ ethereumjs-account@2.0.5
    │ └─┬ ethereumjs-util@5.2.0
    │   └── keccak@1.4.0  deduped
    └─┬ ethereumjs-block@2.2.0
      └─┬ ethereumjs-util@5.2.0
        └── keccak@1.4.0  deduped
```

node 12 only supported by keccak v2.1.0 (https://github.com/cryptocoinjs/keccak/releases)

More info on the error log

```
keccak.target.mk:127: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/home/nebulis/IdeaProjects/opencerts-website/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.20.13-042013-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nebulis/IdeaProjects/opencerts-website/node_modules/keccak
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nebulis/.npm/_logs/2020-01-17T04_26_07_547Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

```

**Comment by Nebulis** [comment]
fixed
